name: Sync Fork and Notify

on:
  schedule:
    - cron: '30 22 * * *' # Runs daily at 04:00 AM IST (10:30 PM UTC)
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Fork with Full History
      - name: Checkout Fork
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Step 2: Debug Git Remotes (Optional)
      - name: Debug Git Remotes
        run: git remote -v

      # Step 3: Set Upstream and Fetch Updates with Retry Logic
      - name: Set Upstream and Fetch Updates
        run: |
          git remote add upstream https://github.com/ruanyf/weekly.git || true
          for i in {1..3}; do
            git fetch upstream || sleep 10;
          done

      # Step 4: Merge Updates from Upstream into Fork
      - name: Merge Updates
        id: merge
        run: |
          git checkout main
          git merge upstream/main --ff-only || echo "No new updates to merge"

      # Step 5: Push Changes Back to Fork if Merged Successfully
      - name: Push Changes to Fork
        if: success() && steps.merge.outcome == 'success'
        run: git push origin main

      # Step 6: Notify via Telegram Bot if Sync Successful
      - name: Notify Telegram Bot
        if: success() && steps.merge.outcome == 'success'
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          LATEST_COMMIT=$(git log -1 --pretty=format:"%s")
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="✅ Sync completed! Latest commit message: ${LATEST_COMMIT}"
