name: Sync Fork and Notify

on:
  schedule:
    - cron: '30 22 * * *' # Runs daily at 04:00 AM IST (10:30 PM UTC)
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Fork with Full History
      - name: Checkout Fork
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Step 2: Add Upstream Repository and Fetch Updates
      - name: Add Upstream and Fetch Updates
        run: |
          git remote add upstream https://github.com/ruanyf/weekly.git || true
          git fetch upstream

      # Step 3: Detect Default Branch of Upstream Repository
      - name: Detect Default Branch
        id: default_branch
        run: |
          DEFAULT_BRANCH=$(git remote show upstream | grep 'HEAD branch' | awk '{print $NF}')
          echo "default_branch=$DEFAULT_BRANCH" >> $GITHUB_ENV

      # Step 4: Checkout Default Branch and Merge Updates
      - name: Checkout and Merge Updates
        run: |
          git checkout ${{ env.default_branch }}
          git merge upstream/${{ env.default_branch }} --ff-only || echo "No new updates to merge"

      # Step 5: Push Changes Back to Fork if Merged Successfully
      - name: Push Changes to Fork
        if: success()
        run: git push origin ${{ env.default_branch }}

      # Step 6: Notify via Telegram Bot if Sync Successful
      - name: Notify Telegram Bot
        if: success()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          LATEST_COMMIT=$(git log -1 --pretty=format:"%s")
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="✅ Sync completed! Latest commit message: ${LATEST_COMMIT}"
